apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-grpc-image-resizer
  name: go-grpc-image-resizer
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: go-grpc-image-resizer
status:
  loadBalancer: {}
