apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-test-consumer
  name: node-test-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-test-consumer
  strategy: {}
  template:
    metadata:
      labels:
        app: node-test-consumer
    spec:
      containers:
      - image: bensooraj/demo-node-consumer:v1
        name: demo-node-consumer
        envFrom:
          - configMapRef:
              name: kafka-client-config
        volumeMounts:
        - name: persistent-storage
          mountPath: /app/image_uploads
        resources: {}
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: efs-claim
status: {}
